### ISSUE TITLE
Amazing work！

### ISSUE THREAD

**Issue by xueyinhualuo** [dusty-nv/turbo2#1]
Your turbo2 looks very powerful！ I am a beginner of embedded system and SLAM system fan from china. I have a nvidia jetson tx1 and a ZED stereo camera. Would you mind give me your blog or instruction about how to build a turbo2? Any help will be appreciate.

**Comment by xueyinhualuo** [comment]
By the way, the link of "24V 12A motor controllers" seems wrong in your BoM.md.

**Comment by Russ76** [comment]
Dusty: It is exciting to find this project. The robot I am constructing is much like this but a little different. Mine has a Sabertooth 2x25 motor controller. (Which is an excellent unit, by the way.) Today I bought a Bluetooth controller like you use, so that code will work. (I had a joystick) My machine doesn't have Lidar. How do I modify the code to bypass the Lidar? Will it still work? I commented out the Lidar portion in turbo2/Cmakelists.txt. Most of the software downloaded fine into my Jetson TX1 but a few files were mentioned as being missing. It took a long time and when it was done, not so much disk space was used.

**Comment by dusty-nv** [comment]
Hi Russ!

The usage of the LIDAR will automatically be disabled when it is not able to be properly initialized.   You can grep Rover.cpp for usage of the rpLIDAR object.

I've seen the Sabertooth online before, I'll have to pick one up.  Right now I am using mostly Polulu components for the motor and servo drivers.

Be aware that the turbo2 and rovernet repos are under development, but we can collaborate. 

Best regards,
Dusty

On May 2, 2016 4:44 PM, Russ Hall notifications@github.com wrote:

Dusty: It is exciting to find this project. The robot I am constructing is much like this but a little different. Mine has a Sabertooth 2x25 motor controller. (Which is an excellent unit, by the way.) Today I bought a Bluetooth controller like you use, so that code will work. (I had a joystick) My machine doesn't have Lidar. How do I modify the code to bypass the Lidar? Will it still work? I commented out the Lidar portion in turbo2/Cmakelists.txt. Most of the software downloaded fine into my Jetson TX1 but a few files were mentioned as being missing. It took a long time and when it was done, not so much disk space was used.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://github.com/dusty-nv/turbo2/issues/1#issuecomment-216373706

---

This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by

## reply email and destroy all copies of the original message.

**Comment by dusty-nv** [comment]
xueyinhualuo wrote:

> By the way, the link of "24V 12A motor controllers" seems wrong in your BoM.md.

Thank you, I have updated [BoM.md](https://github.com/dusty-nv/turbo2/blob/master/BoM.md).
